// Citaterne til Corne-øvelsen. Én fil, to læsere: oev.html (browser) og oev.py (terminal).
// Filip dikterer, Claude tilføjer. Én linje pr. citat: forfatter, komma, tekst, begge i enkelte anførselstegn; apostrof skrives med backslash foran.
const CITATER = [
 ['Alan Watts','The only way to make sense out of change is to plunge into it, move with it, and join the dance.'],
 ['Alan Watts','Muddy water is best cleared by leaving it alone.'],
 ['Alan Watts','You are an aperture through which the universe is looking at and exploring itself.'],
 ['Alan Watts','Trying to define yourself is like trying to bite your own teeth.'],
 ['Alan Watts','The meaning of life is just to be alive. It is so plain and so obvious and so simple. And yet, everybody rushes around in a great panic as if it were necessary to achieve something beyond themselves.'],
 ['Alan Watts','This is the real secret of life: to be completely engaged with what you are doing in the here and now. And instead of calling it work, realize it is play.'],
 ['Alan Watts','No valid plans for the future can be made by those who have no capacity for living now.'],
 ['Alan Watts','Man suffers only because he takes seriously what the gods made for fun.'],
 ['Alan Watts','To have faith is to trust yourself to the water. When you swim you don\'t grab hold of the water, because if you do you will sink and drown. Instead you relax, and float.'],
 ['Alan Watts','Problems that remain persistently insoluble should always be suspected as questions asked in the wrong way.'],
 ['Alan Watts','You are that vast thing that you see far, far off with great telescopes.'],

 ['Eckhart Tolle','Realize deeply that the present moment is all you ever have.'],
 ['Eckhart Tolle','Life is the dancer and you are the dance.'],
 ['Eckhart Tolle','Whatever the present moment contains, accept it as if you had chosen it.'],
 ['Eckhart Tolle','The primary cause of unhappiness is never the situation but your thoughts about it.'],
 ['Eckhart Tolle','Acknowledging the good that you already have in your life is the foundation for all abundance.'],
 ['Eckhart Tolle','Wherever you are, be there totally.'],
 ['Eckhart Tolle','Stress is caused by being here but wanting to be there.'],
 ['Eckhart Tolle','The past has no power over the present moment.'],
 ['Eckhart Tolle','Awareness is the greatest agent for change.'],
 ['Eckhart Tolle','Sometimes letting things go is an act of far greater power than defending or hanging on.'],
 ['Eckhart Tolle','Give up defining yourself, to yourself or to others. You won\'t die. You will come to life.'],
 ['Eckhart Tolle','Where there is anger, there is always pain underneath.'],

 ['Mooji','Step into the fire of self-discovery. This fire will not burn you, it will only burn what you are not.'],
 ['Mooji','Your heart is the light of this world. Don\'t cover it with your mind.'],
 ['Mooji','Don\'t remind the world that it is sick and troubled. Remind it that it is beautiful and free.'],
 ['Mooji','When you can bear your own silence, you are free.'],
 ['Mooji','The mind is like the wind. You\'re trying to stop the wind, dressed as a kite.'],
 ['Mooji','Feelings are just visitors, let them come and go.'],
 ['Mooji','You have to die as a seed to live as a tree.'],
 ['Mooji','Even the finest experiences are not what you are.'],
 ['Mooji','Be a witness to life unfolding by itself.'],

 ['David Deida','Live with your lips pressed against your fears, kissing your fears, neither pulling back nor aggressively violating them.'],
 ['David Deida','The superior man is not seeking fulfillment through work and woman, because he is already full. For him, work and intimacy are opportunities to give his gifts, and to be vanished in the bliss of giving.'],
 ['David Deida','Unadorned suffering is the bedmate of masculine growth. Only by staying intimate with your personal suffering can you feel through it to its source.'],
 ['David Deida','Every moment of your life is either a test or a celebration.'],
 ['David Deida','You are either living fully, giving your gift in the midst of those challenges, even today, or you are waiting for an imaginary future which will never come.'],
 ['David Deida','Your purpose must come before your relationship.'],
 ['David Deida','Stop hoping for a completion of anything in life.'],
 ['David Deida','Be willing to change everything in your life.'],
 ['David Deida','Live as if your father were dead.'],
 ['David Deida','He must be capable of not knowing what to do with his life, entering a period of unknowingness and waiting for a vision or a new form of purpose to emerge.'],

 ['Joe Hudson','People don\'t want you to be perfect; what they want is to feel connected with you.'],
 ['Joe Hudson','If you can\'t say no easily, then you can\'t be trusted.'],
 ['Joe Hudson','Unspoken expectations are premeditated resentments.'],
 ['Joe Hudson','Joy is the matriarch of a family of emotions, and she won\'t come into a house where her children aren\'t welcome.'],
 ['Joe Hudson','If you had to do it perfectly, you\'d stop doing it.'],
 ['Joe Hudson','What if the purposelessness is actually freedom?'],
 ['Joe Hudson','It\'s an undoing, not a doing.'],
 ['Joe Hudson','A should is two desires in competition.'],
 ['Joe Hudson','Make your work something lovely for you to do and you won\'t procrastinate.'],
 ['Joe Hudson','Just admit to the reality of the situation.'],

 ['Julien Blanc','Achieving your transformation is a process of removing, not accumulating.'],
];
